MDW-3627: Ohif viewer integration
MDWio/ohif-viewer pull request #1
Opened 2022-12-02 18:31 UTC by alexandrborisovyg

Подробности в [Jira тикете](https://mdwebio.atlassian.net/browse/MDW-3627)

2022-12-07 10:07 UTC, justvamp requested changes

2022-12-07 10:07 UTC, justvamp commented on package.json
> +    "moment-timezone": "^0.5.39"
можно сразу заюзать dayjs: она работает аналогично, но весит во много раз меньше (для браузера довольно критично может быть)

2022-12-07 10:07 UTC, justvamp commented on package.json
> +    "moment-timezone": "^0.5.39"
https://day.js.org/en/

2022-12-07 10:07 UTC, justvamp commented on extensions/cornerstone/src/init.js
> +  // end
так нужно закомментить или нет?

2022-12-07 10:07 UTC, justvamp commented on platform/viewer/.env
> +APP_CONFIG=config/default_nanox.js
так может просто дефолтный конфиг пофиксать как нужно, чем новый создавать?

2022-12-07 10:07 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +        return;
`updatedStudies` - всегда undefined, т.к. `updateStudies()` ничего не возвращает.
Соответственно, тут всегда будет выходиться.

2022-12-07 12:21 UTC, alexandrborisovyg commented on extensions/cornerstone/src/init.js
> +  // end
убрал комментарии, они уже не актуальны

2022-12-07 12:21 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +        return;
так то это я перенес с ViewerLocalFileData, то есть это их логика, но согласен здесь код странный, убрал это проверку и теперь всегда просто будет выполняться return, поведение вьюера это не меняет

2022-12-09 13:51 UTC, justvamp commented on package.json
> +    "moment-timezone": "^0.5.39"
давай это тогда в следующий тикет перенесём

2022-12-09 13:52 UTC, alexandrborisovyg commented on package.json
> +    "moment-timezone": "^0.5.39"
да, хорошо, как улучшение

2022-12-09 13:52 UTC, justvamp approved these changes

2022-12-09 13:53 UTC, merged