MDW-4912: OpenSearch. Viewer failing to show a large study
MDWio/ohif-viewer pull request #18
Opened 2024-09-24 07:45 UTC by alexandrborisovyg

Подробности в тикете

2024-09-25 05:12 UTC, jimOnAir requested changes

2024-09-25 05:12 UTC, jimOnAir commented on platform/viewer/src/routes/StandaloneRouting.js
> +        const data = JSON.parse(oReq.responseText);
что если будет ошибка парсинга?

2024-09-25 05:12 UTC, jimOnAir commented on platform/viewer/src/routes/StandaloneRouting.js
> +        if (!data.studies || !data.studies.length) {
не нужно ли проверить, что data.studies - массив? Ну и явно проверить что длина больше 0

2024-09-25 09:23 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +        const data = JSON.parse(oReq.responseText);
обернул в try catch

2024-09-25 09:23 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +        if (!data.studies || !data.studies.length) {
добавил проверку

2024-09-25 14:19 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +              studyInstanceUIDs: [],
зачем нужен этот пустой массив?

2024-09-26 07:52 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +      if (token) {
`else if` тут будет логичнее

2024-09-26 08:15 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +      if (token) {
fixed

2024-09-26 08:23 UTC, justvamp approved these changes

2024-09-27 08:21 UTC, jimOnAir approved these changes

2024-09-27 08:45 UTC, merged