MDW-3726: Ohif. Unsupported color mode
MDWio/ohif-viewer pull request #3
Opened 2023-02-03 13:46 UTC by alexandrborisovyg

Добавлена проверка для поля PhotometricInterpretation для displaySet по аналогии проверки модальности
В случае если значение равно 'YBR_FULL', выводить читаемую ошибку в консоли и в всплывающем уведомлении пользователю

2023-02-03 16:15 UTC, justvamp requested changes

2023-02-03 16:15 UTC, justvamp commented on platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
> +      if (displaySet.images[0]._data.metadata.PhotometricInterpretation === 'YBR_FULL') {
Что если в `displaySet` нет массива имиджей? или нулевого имиджа в массиве? или `_data` в имидже? или `metadata`? или `PhotometricInterpretation`?

В общем, стоит это обложить знаками вопроса вдоль и поперёк, иначе одни ошибки в консоли заменим на другие.

2023-02-06 12:40 UTC, alexandrborisovyg commented on platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
> +      if (displaySet.images[0]._data.metadata.PhotometricInterpretation === 'YBR_FULL') {
добавил проверки на null для каждого поля и подполя объекта

2023-02-07 08:25 UTC, justvamp approved these changes

2023-02-08 06:28 UTC, justvamp approved these changes

2023-02-08 06:29 UTC, merged