MDW-3632: New viewer. Ohif viewer improvements
MDWio/ohif-viewer pull request #4
Opened 2023-02-28 15:32 UTC by alexandrborisovyg

Подробности в тикете

2023-03-01 05:00 UTC, justvamp commented
Не хотим тут синкнуть с main repo?
<img width="242" alt="Screenshot 2023-03-01 at 12 59 43" src="https://user-images.githubusercontent.com/521151/222048842-a73378e6-7967-49c8-8723-a242745ab246.png">

2023-03-01 15:02 UTC, alexandrborisovyg commented
> Не хотим тут синкнуть с main repo? <img alt="Screenshot 2023-03-01 at 12 59 43" width="242" src="https://user-images.githubusercontent.com/521151/222048842-a73378e6-7967-49c8-8723-a242745ab246.png">

смерджил последний мастер в ветку

2023-03-02 10:44 UTC, justvamp requested changes
Непонятно, в чём фикс.

2023-03-02 10:44 UTC, justvamp commented on platform/viewer/src/components/StudyPrefetcher.js
> +import cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader';
не убрал импорт

2023-03-02 10:57 UTC, alexandrborisovyg commented on platform/viewer/src/components/StudyPrefetcher.js
> +import cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader';
fixed

2023-03-02 11:07 UTC, merged