MDW-3793: Data mon. Ability to open DICOM in the viewer from S3
MDWio/ohif-viewer pull request #6
Opened 2023-04-05 15:54 UTC by alexandrborisovyg

Подробности в тикете

2023-04-10 03:49 UTC, justvamp requested changes

2023-04-10 03:49 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +              metadataProvider.addImageIdToUIDs(url, {
это нормально, что тут url используется вместо imageId?

2023-04-10 03:49 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +        data.studies[0].series[0].instances[0].url = 'dicomweb:' + url;
Почему только в один элемент добавляется url? А остальные не нужно изменить? Или это вообще лишнее?

Плюс массивы же могут быть пустыми теоретически? А тут считается, что на всех уровнях вложенности есть как минимум один элемент.

2023-04-10 03:49 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +      if (url && json) {
Проверка на наличие url уже есть выше. Тогда получается, что тут хватит лишь проверки на наличие json.

2023-04-11 15:57 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +              metadataProvider.addImageIdToUIDs(url, {
сейчас поменялся код, тут опять imageId, но по сути это тоже самое, это просто url-ка к файлу (в нашем случае к S3), но для консистенции кода оставил imageId

2023-04-11 15:57 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +        data.studies[0].series[0].instances[0].url = 'dicomweb:' + url;
на стороне OSD формируется json с уже одним инстансом, так что первый (нулевой) элемент не должен быть пустым. По новой логике нулевой элемент заполняется отдельно, так как его не нужно реплицировать, как последующие.

добавил поддержку нескольких файлов (ссылок): в images получаются ссылки, и по каждой из них добавляется новая серия в json. В случае если у инстанса нет серии (так может быть в объектах OpenSearch, но как правило все файлы имеют отдельную серию), то инстанс добавляется в последнюю серию.

2023-04-11 15:57 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +      if (url && json) {
обновил код, теперь флоу такие, для маркетплэйса используется url, а OSD (OpenSearch Dashboards) использует images (массив ссылок на файлы) и json (это темплейт json с метаданными для одного объекта), дальше он используется для добавления новых серий с инстансами. Так сделал, чтобы при большом кол-ве файлов не падал запрос на слишком длинный query с json

2023-04-12 07:16 UTC, justvamp requested changes

2023-04-12 07:16 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +        const arrayOfSOPInstanceUID = data.studies[0].series[0].instances[0].metadata.SOPInstanceUID.split(
для metadata можно завести отдельную константу и не копипастить весь этот паровоз по всему файлу

2023-04-12 07:16 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
>              }
Очень много претензий к этому куску кода. Это не уровень middle developer.

1. Не очень понятно, зачем изменять _наживую_ `data.studies[0]`, чтобы его вернуть в `resolve`, если можно новый массив стадий создать с нуля и уже его вернуть.
2. Логика заполнения этого массива стадий не должна зависеть от индекса (нулевой, последний, остальные) - код можно и нужно написать так, чтобы это избежать.
3. Для этого придётся предварительно подготовить массивы, уже содержащие однообразные данные. Так ты разделишь логику подготовки данных от логики заполнения массива стадий (сейчас всё в кучу) - это и поможет улучшить читабельность.

Станет намного красивее, вот увидишь.

2023-04-12 07:32 UTC, justvamp requested changes

2023-04-12 07:32 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +              });
то есть если пришло, допустим, 5 SeriesInstanceUID и 10 SOPInstanceUID, то первые 4 имиджа будут в отдельных сериях (по одному имиджу в серии), а остальные 6 будут в последней пятой серии?

2023-04-12 11:20 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +        const arrayOfSOPInstanceUID = data.studies[0].series[0].instances[0].metadata.SOPInstanceUID.split(
fixed

2023-04-12 11:20 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
>              }
Отрефакторил:
1. Работаю с пустой копией data.studies[0] и уже ее возвращаю
2. Избавился от индексов, перед основным циклом составляю массив, содержащий в себе все необходимые поля

2023-04-12 11:20 UTC, alexandrborisovyg commented on platform/viewer/src/routes/StandaloneRouting.js
> +              });
да, большинство объектов в OpenSearch имееют такую структуру:
"SOPInstanceUID": [
      "1.2.392.200036.9125.9.0.571452553.182693048.644841456",
      "1.2.392.200036.9125.9.0.571452553.157396152.644841456"
    ],
"SeriesInstanceUID": [
      "1.2.392.200036.9125.3.18417211138240127.656722048.320424",
      "1.2.392.200036.9125.3.18417211138240127.656722048.320423"
    ],
В таком стандартном случае каждый имидж находится в отдельной серии

При этом могут быть такие объекты:
"SOPInstanceUID": [
      "1.2.410.200013.1.310.1.202206181720418570264",
      "1.2.410.200013.1.310.1.202206181720421140265"
    ],
"SeriesInstanceUID": "1.2.410.200013.1.310.1.202206181720417310263",
Когда серий для всех имиджей не хватает, и в таком случае я добавляю их в последнюю серию

Я не нашел информации по матчингу SeriesInstanceUID по SOPInstanceUID, и закономерности в UID общей нет, они все отличаются, так что оставил этот вариант

2023-04-12 15:03 UTC, justvamp commented on platform/viewer/src/routes/StandaloneRouting.js
> +              });
странная схема, но ок )

2023-04-26 08:26 UTC, justvamp approved these changes

2023-04-26 08:40 UTC, merged